<?php

/**
 * Implements hook_schema().
 */
function xhprof_tests_schema() {
  return array(
    'xhprof_tests_profile_run' => array(
      'description' => 'The base table for Xhprof profile runs.',
      'fields' => array(
        'rid' => array(
          'description' => 'The primary identifier for a run.',
          'type' => 'serial',
          'unsigned' => TRUE,
          'not null' => TRUE,
        ),
        'test_id' => array(
          'description' => 'The current Simpletest test_id this run is associated with.',
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => TRUE,
          'default' => 0,
        ),
        'run_type' => array(
          'description' => 'The type of this run, used so we can usefully compare the data.',
          'type' => 'varchar',
          'length' => 64,
          'not null' => TRUE,
          'default' => '',
        ),
        'run_data' => array(
          'description' => 'The serialized data for this run.',
          'type' => 'text',
          'not null' => TRUE,
          'size' => 'big',
        ),
      ),
      'indexes' => array(
        'run_type' => array('run_type'),
        'test_id' => array('test_id'),
      ),
      'primary key' => array('rid'),
    ),
  );
}

